# Generated by Django 2.0.7 on 2019-03-12 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emfs', '0007_auto_20190312_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50, unique=True)),
                ('emf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emfs.Emf')),
            ],
        ),
    ]
