# Generated by Django 2.0.7 on 2019-03-12 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190312_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='emf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emfs.Emf'),
        ),
    ]
