# Generated by Django 2.0.7 on 2019-03-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190312_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='emf',
        ),
    ]
