# Generated by Django 2.0.7 on 2019-03-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0007_auto_20190312_1013'),
        ('events', '0005_remove_event_emf'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='emf',
            field=models.ManyToManyField(blank=True, null=True, to='emfs.Emf'),
        ),
    ]
