# Generated by Django 2.0.7 on 2019-03-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190312_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='emf',
        ),
    ]
