# Generated by Django 2.0.7 on 2019-03-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_emf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
