# Generated by Django 2.0.7 on 2019-03-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190312_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
