# Generated by Django 2.0.7 on 2019-03-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20190312_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Title',
            new_name='event',
        ),
    ]
