# Generated by Django 2.0.7 on 2019-03-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0006_auto_20181206_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emf',
            old_name='event',
            new_name='events_handled',
        ),
    ]
