# Generated by Django 2.0.7 on 2019-03-12 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_emf'),
        ('emfs', '0007_auto_20190312_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='emf',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Event'),
        ),
    ]
