# Generated by Django 2.0.7 on 2019-03-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0011_auto_20190312_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emf',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
