# Generated by Django 2.0.7 on 2019-03-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0012_auto_20190312_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emf',
            name='specialty',
        ),
    ]
