# Generated by Django 2.0.7 on 2019-03-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0013_remove_emf_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='emf',
            name='specialty',
            field=models.CharField(blank=True, default='Birthday', max_length=50, null=True),
        ),
    ]
