# Generated by Django 2.0.7 on 2019-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0014_emf_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emf',
            name='specialty',
            field=models.CharField(default='', max_length=20),
        ),
    ]
