# Generated by Django 2.0.7 on 2019-03-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0016_auto_20190312_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emf',
            name='specialty',
        ),
        migrations.AlterField(
            model_name='emf',
            name='events_handled',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('dwedding', 'DWedding'), ('anniversary', 'Anniversary'), ('festive', 'Festive'), ('special', 'Special'), ('corporate', 'Corporate')], max_length=50),
        ),
    ]
