# Generated by Django 2.0.7 on 2019-03-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0019_emf_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emf',
            name='slug',
            field=models.SlugField(default='abcd'),
        ),
    ]
