# Generated by Django 2.0.7 on 2019-03-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emfs', '0020_auto_20190313_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emf',
            name='city',
        ),
    ]
