# Generated by Django 2.0.7 on 2019-03-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_guestuser_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestUser',
        ),
    ]
