# Generated by Django 2.0.7 on 2019-03-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emfs', '0020_auto_20190313_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('emf', models.ManyToManyField(related_name='efirms', to='emfs.Emf')),
            ],
        ),
    ]
