# Generated by Django 2.0.7 on 2019-03-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='emf',
            field=models.ManyToManyField(to='emfs.Emf'),
        ),
    ]
