# Generated by Django 2.0.7 on 2019-03-20 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20190319_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cities', 'verbose_name_plural': 'Cities'},
        ),
    ]
