# Generated by Django 2.0.7 on 2019-03-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_emf'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(blank=True, choices=[('lucknow', 'Lucknow'), ('delhi', 'Delhi'), ('mathura', 'Mathura'), ('mumbai', 'Mumbai'), ('kolkata', 'Kolkata')], max_length=60, null=True),
        ),
    ]
