# Generated by Django 2.0.7 on 2019-03-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='emf',
        ),
    ]
