# Generated by Django 2.0.7 on 2019-03-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_emf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='booking_date',
        ),
    ]
