# Generated by Django 2.0.7 on 2019-03-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20190316_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
