# Generated by Django 2.0.7 on 2019-03-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('bookings', '0012_auto_20190318_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(blank=True, choices=[('lucknow', 'Lucknow'), ('delhi', 'Delhi'), ('mathura', 'Mathura'), ('mumbai', 'Mumbai'), ('kolkata', 'Kolkata')], max_length=60, null=True),
        ),
    ]
