# Generated by Django 2.0.7 on 2019-03-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20190318_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='city2',
        ),
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
        ),
    ]
