# Generated by Django 2.0.7 on 2019-03-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('bookings', '0014_auto_20190318_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.Price'),
        ),
    ]
