# Generated by Django 2.0.7 on 2019-03-31 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Detail'),
        ),
    ]
