# Generated by Django 2.0.7 on 2019-03-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_auto_20190331_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='dj_entertainment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detail',
            name='photography',
            field=models.BooleanField(default=True),
        ),
    ]
