# Generated by Django 2.0.7 on 2019-03-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_auto_20190331_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='people',
            field=models.IntegerField(default=0),
        ),
    ]
