# Generated by Django 2.0.7 on 2019-03-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_auto_20190331_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='people',
            field=models.IntegerField(),
        ),
    ]
