# Generated by Django 2.0.7 on 2019-03-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('paid', 'Paid'), ('done', 'Done'), ('refunded', 'Refunded')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amt',
            field=models.DecimalField(blank=True, decimal_places=3, default=100, max_digits=100, null=True),
        ),
    ]
