# Generated by Django 2.0.7 on 2019-03-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190320_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('paid', 'Paid'), ('done', 'Done'), ('refunded', 'Refunded')], default='created', max_length=30, null=True),
        ),
    ]
