# Generated by Django 2.0.7 on 2019-03-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
