# Generated by Django 2.0.7 on 2019-03-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amt',
        ),
    ]
